### ISSUE TITLE
Recipe LICENSE isn't correct

### ISSUE THREAD

**Issue by rossburton** [kpmteam/meta-teleport#1]
The teleport recipe claims that the package is MIT licensed:

https://github.com/kpmteam/meta-kpmpower/blob/eab9e7b2621903811282edfa5ba7c186a2ab2a28/recipes-core/teleport/teleport_11.3.20.bb#L2C2-L2C2

I doubt very much that the teleport client is MIT licensed.  The LICENSE field is the license of the *resulting packages* not the recipe itself.

**Comment by mdsketch** [comment]
You are correct, let me fix that, it's apache2.0 according to the repository, I thought I had it set up as that. https://github.com/gravitational/teleport/

**Comment by mdsketch** [comment]
PR #2 opened to address this

**Comment by rossburton** [comment]
Oh if this isn't a closed binary then a proper recipe would build it from scratch :)

**Comment by mdsketch** [comment]
Thats a good point, I'm working on that, for now I am just cloning precompiled ones
